sudo: false

language: node_js

node_js:
  - '11'

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn test

after_success:
  - sh src/push.sh

env:
  - CXX=g++-4.9

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libcairo2-dev
      - libjpeg8-dev
      - libpango1.0-dev
      - libgif-dev
      - librsvg2-dev
      - g++-4.9
